.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie1 - Debug ]----------"
	@cd "zadanie1" && "$(MAKE)" -f  "zadanie1.mk"
clean:
	@echo "----------Cleaning project:[ zadanie1 - Debug ]----------"
	@cd "zadanie1" && "$(MAKE)" -f  "zadanie1.mk" clean
