.PHONY: clean All

All:
	@echo "----------Building project:[ zadanie2 - Debug ]----------"
	@cd "zadanie2" && "$(MAKE)" -f  "zadanie2.mk"
clean:
	@echo "----------Cleaning project:[ zadanie2 - Debug ]----------"
	@cd "zadanie2" && "$(MAKE)" -f  "zadanie2.mk" clean
